### ISSUE TITLE
알고리즘 실행에 걸린 시간 관련 문제

### ISSUE THREAD

**Issue by MaccBass** [m00nhyunw00/AlgorithmProj_findMeetingPlace#8]
start_time과 end_time 2개의 변수에 time.time()으로 현재 시간을 입력받고 이들의 차로 계산을 하는데,
알고리즘 속도가 매우 빠른 것인지, 제대로 반영이 안된건지 이 값이 0.0으로 출력되는 경우가 많음.
후자일 확률이 매우 높으므로 한번 검토 필요

**Comment by m00nhyunw00** [comment]
아무리 빨라도 0.0은 말이 안되므로 후자일 확률 높아보임

**Comment by MaccBass** [comment]
시간 측정 함수를 time.perf_counter()으로 변경
